-- MySQL Script generated by MySQL Workbench
-- Wed 11 Nov 2015 03:03:21 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sapi
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sapi
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sapi` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `sapi` ;

-- -----------------------------------------------------
-- Table `sapi`.`PROJETOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sapi`.`PROJETOS` (
  `id` INT NOT NULL,
  `TITULO` VARCHAR(45) NOT NULL,
  `PROGRAMA` VARCHAR(45) NOT NULL,
  `ANO` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
