-- MySQL Script generated by MySQL Workbench
-- Wed 11 Nov 2015 03:05:59 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema siatex
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema siatex
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siatex` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `siatex` ;

-- -----------------------------------------------------
-- Table `siatex`.`PROPOSTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siatex`.`PROPOSTAS` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `TITULO` VARCHAR(45) NOT NULL,
  `MODALIDADE` VARCHAR(45) NOT NULL,
  `REGISTRO` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
