-- MySQL Script generated by MySQL Workbench
-- Wed 11 Nov 2015 03:05:59 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema siatex
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `siatex` ;

CREATE SCHEMA IF NOT EXISTS `siatex` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `siatex` ;

-- -----------------------------------------------------
-- Table `siatex`.`propostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siatex`.`propostas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(45) NOT NULL,
  `modalidade` VARCHAR(45) NOT NULL,
  `elaborador` VARCHAR(45) NOT NULL,
  `coordenador` VARCHAR(45) NOT NULL,
  `registro` TINYINT(1) NOT NULL,
  `submissão` TINYINT(1) NOT NULL,
  `ano` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `siatex`.`propostas` (`id` ASC);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
