-- MySQL Script generated by MySQL Workbench
-- Wed 11 Nov 2015 03:05:59 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema siatex
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `siatex` ;

CREATE SCHEMA IF NOT EXISTS `siatex` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `siatex` ;

-- -----------------------------------------------------
-- Table `siatex`.`propostas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siatex`.`propostas` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(250) NOT NULL,
  `modalidade` VARCHAR(250) NOT NULL,
  `elaborador` VARCHAR(250) NOT NULL,
  `coordenador` VARCHAR(250) NOT NULL,
  `ano` VARCHAR(250) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `id_UNIQUE` ON `siatex`.`propostas` (`id` ASC);

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO `siatex`.`propostas` (`id`, `titulo`, `modalidade`, `elaborador`, `coordenador`, `ano`)
VALUES
(1, 'GruPro', 'Projeto', 'Mauricio Pamplona Segundo', 'Rubisley Lemes', '2014'),
(2, 'SisProg', 'Projeto', 'Eduardo Santana de Almeida', 'Mauricio Pamplona Segundo', '2015'),
(3, 'Curso de Programação', 'Curso', 'Mauricio Pamplona Segundo', 'Rubisley Lemes', '2016'),
(4, 'Programa de Residência em Reuso de Software', 'Curso', 'Eduardo Santana de Almeida', 'Ivan do Carmo', '2014');
