-- MySQL Script generated by MySQL Workbench
-- Wed 11 Nov 2015 03:01:37 PM BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema sisbic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sisbic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sisbic` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `sisbic` ;

-- -----------------------------------------------------
-- Table `sisbic`.`planos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sisbic`.`planos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Titulo` VARCHAR(45) NOT NULL,
  `aluno` VARCHAR(45) NOT NULL,
  `relatorio` VARCHAR(45) NOT NULL,
  `status` TINYINT(1) NOT NULL,
  `ano` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
